version: '3'

services:
  instance-1:
    image: node:14-alpine
    depends_on:
      - redis
    container_name: instance-1
    working_dir: /app
    environment:
      APP: 1
    volumes:
      - .:/app
    command: npm start

  instance-2:
    image: node:14-alpine
    depends_on:
      - redis
    container_name: instance-2
    working_dir: /app
    environment:
      APP: 2
    volumes:
      - .:/app
    command: npm start

  instance-3:
    image: node:14-alpine
    depends_on:
      - redis
    container_name: instance-3
    working_dir: /app
    environment:
      APP: 3
    volumes:
      - .:/app
    command: npm start

  instance-4:
    image: node:14-alpine
    depends_on:
      - redis
    container_name: instance-4
    working_dir: /app
    environment:
      APP: 4
    volumes:
      - .:/app
    command: npm start

  instance-5:
    image: node:14-alpine
    depends_on:
      - redis
    container_name: instance-5
    working_dir: /app
    environment:
      APP: 5
    volumes:
      - .:/app
    command: npm start

  redis:
    image: redis:6.0.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
