version: '3'

services:
  instance-1:
    build: .
    depends_on:
      - redis
    environment:
      APP: 1
    container_name: instance-1

  instance-2:
    build: .
    depends_on:
      - redis
    environment:
      APP: 2
    container_name: instance-2

  instance-3:
    build: .
    depends_on:
      - redis
    environment:
      APP: 3
    container_name: instance-3

  instance-4:
    build: .
    depends_on:
      - redis
    environment:
      APP: 4
    container_name: instance-4

  instance-5:
    build: .
    depends_on:
      - redis
    environment:
      APP: 5
    container_name: instance-5

  redis:
    image: redis:6.0.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
